figure(1)
subplot(4,2,1)
histfit(measurement_error(1,:), 20)
subplot(4,2,2)
histfit(measurement_error(2,:), 20)
subplot(4,2,3)
histfit(measurement_error(3,:), 20)
subplot(4,2,4)
histfit(measurement_error(4,:), 20)
subplot(4,2,5)
histfit(measurement_error(5,:), 20)
subplot(4,2,6)
histfit(measurement_error(6,:), 20)
subplot(4,2,7)
histfit(measurement_error(7,:), 20)
subplot(4,2,8)
histfit(measurement_error(8,:), 20)
subplot(4,2,1)
title('Sensor 1')
subplot(4,2,2)
title('Sensor 2')
subplot(4,2,3)
title('Sensor 3')
subplot(4,2,4)
title('Sensor 4')
subplot(4,2,5)
title('Sensor 5')
subplot(4,2,6)
title('Sensor 6')
subplot(4,2,7)
title('Sensor 7')
figure(1)
title('Sensor probability density functions')
title('Sensor 7')
sgtitle('Sensor probability density functions')